### PR TITLE
More enemies

### PR DESCRIPTION
**Pull request by vincetiu8**
Sorry I haven't seemed so active recently, as I was grouping all of these commits into one big PR. This adds more enemies and enemy attributes to the game, including:
- Flying enemies
- Shield enemies
- Explode (suicide) enemies
This adds to #1.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Couple of issues:

- Got this error while messing around in the enemy preview
Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "data/main.py", line 54, in run
    self.draw()
  File "data/main.py", line 63, in draw
    surf = self.current_display.draw()
  File "data/dev_tools.py", line 146, in draw
    hp_surf = enemy.get_hp_surf()
  File "enemies.py", line 122, in get_hp_surf
    hp_surf = pg.Surface((self.hp * 2, 5))
pygame.error: Invalid resolution for Surface
Best way I found to replicate this bug is to go change the towers to neutrophil and increase their stage to 2.

- Got another error when trying to add shields onto polio:
Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "data/main.py", line 52, in run
    self.update()
  File "data/main.py", line 57, in update
    self.current_display.update()
  File "data/dev_tools.py", line 114, in update
    start.update()
  File "data/game.py", line 478, in update
    self.game.enemies.add(Enemy(
  File "data/enemies.py", line 25, in __init__
    self.shield_max_hp = data["shield_hp"]
KeyError: 'shield_hp'

- In the tower preview, an enemy explodes on death and destroys a tower, the path is drawn as if all towers were ignored instead of only the one that gets destroyed. The path stays this way even if the towers are reloaded.

- This can be added in a future PR but I think the whole explode on death mechanic is way too harsh to be a one-hit kill for towers. Adding tower HP could make it a bit less brutal.

EDIT: Also got this error when trying to start a level

Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "data/main.py", line 51, in run
    self.events()
  File "data/main.py", line 88, in events
    self.set_display(self.display_keys[result], args)
  File "data/main.py", line 91, in set_display
    display.new(args)
  File "data/game.py", line 56, in new
    self.new_game()
  File "data/game.py", line 139, in new_game
    self.draw_tower_bases_wrapper()
  File "data/game.py", line 310, in draw_tower_bases_wrapper
    self.draw_tower_bases_wrapper()
  File "data/game.py", line 310, in draw_tower_bases_wrapper
    self.draw_tower_bases_wrapper()
  File "data/game.py", line 310, in draw_tower_bases_wrapper
    self.draw_tower_bases_wrapper()
  [Previous line repeated 991 more times]
RecursionError: maximum recursion depth exceeded

**Comment by Graphcalibur** [comment]
Also, what does the "scroll position" attribute for the Rabies enemy do?

**Comment by vincetiu8** [comment]
> Also, what does the "scroll position" attribute for the Rabies enemy do?

Scroll position currently does nothing for enemies where there aren't enough attributes to be 'scrollable', or all of the attributes can still be displayed on the page. Its utility can be seen in the tower preview, as it is the same implementation, built into the UI.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
Most of the issues have been fixed though now neutrophil can't kill enemies at all. Enemies don't seem to have any HP left but they are still alive.

**Comment by vincetiu8** [comment]
Fixed @Graphcalibur.

**Review by Graphcalibur — APPROVED** [review]
LGTM!

**Pull request merged**
