### PR TITLE
Cleaned up folders, fixed images and added wave text

### PR DESCRIPTION
**Pull request by Graphcalibur**
List of changes:
- Addressing #48, the img folder is now a lot cleaner with subfolders made for UI, enemies, and towers
- Common cold and Hepatitis A sprites are now at their intended size
- Updated UI to display the wave count

(also edited the enemy and wave data to make them a bit tougher but that's not important)

### CODE REVIEW

**Review by vincetiu8 — CHANGES_REQUESTED** [review]
Everything looks good, but I intended to make all the enemies a smaller size than they originally were. This is to enable movement animations, which I will implement in a future PR. Could you change the sizes back?

**Comment by Graphcalibur** [comment]
Sorry, should be reverted now

**Comment by vincetiu8** [comment]
Did you make a commit? They're still big on mine...

**Comment by Graphcalibur** [comment]
Whoops. Should (actually) be reverted now.

**Review by vincetiu8 — APPROVED** [review]
LGTM!

**Pull request merged**
