### PR TITLE
Add targeting options to the game

### PR DESCRIPTION
**Pull request by vincetiu8**
This adds 4 options:
- First
- Last
- Strong
- Weak

Slow towers now target enemies that haven't been slowed and shield breakers now target enemies with shields.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Got this error when trying to test the AI of shield breaker towers in the Mild Mouth level:
file "data/towers.py", line 324, in update
    if self.current_enemy != None and ((self.different_shield_damage and self.current_enemy.shield_hp == 0) or \
AttributeError: 'Enemy' object has no attribute 'shield_hp'.

Some of the targeting options also don't seem to work properly. Goblet cells still shoot slowed enemies, and the "First" and "Last" targeting options have their functionality swapped.

Lastly, after clicking "Next Wave" in the Mild Mouth level, clicking the targeting option of a tower won't update the label until the first enemy has spawned.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
LGTM, only remaining thing that needs to be changed is that I think the names for the targeting options "First" and "Last" should be changed. "First" makes it sound like the towers will aim for the enemy nearest to the start when actually they aim for the enemy closest to the end and vice versa for "Last".

**Comment by vincetiu8** [comment]
Oh what? I didn't realize that and copied the targeting from other tower defense games, where first refers to the first enemy (and therefore the one closest to the goal) and last refers to the last enemy (and therefore the one furthest from the goal). I'm not sure if we should change it, perhaps just something to remember during playtesting and if people feel weird about it then maybe we can change it?

**Comment by Graphcalibur** [comment]
Oh, alright then.

**Pull request merged**
