### PR TITLE
Optimize 3

### PR DESCRIPTION
**Pull request by vincetiu8**
This PR adds support to skip the middle scale in the game, fixing #269.

This is still a draft. @Graphcalibur I don't have too much experience working with the menu, so I left some groundwork in to implement the same kind of thing in the menu but can't get it working. Could you look at this?

### CODE REVIEW

**Comment by Graphcalibur** [comment]
Aight, I'll see if I can get the menu scaling to work.

**Comment by Graphcalibur** [comment]
I changed the code so that the body, level buttons, and level infos are drawn onto the Menu surface directly instead of on the temporary surface. So there's still a bit of transform.scale() usage for the level buttons and level infos unfortunately, but I don't think this matters that much since Menu lag isn't as much of an issue as Game lag

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
The Game UI is bugged and doesn't scale properly if the screen size is changed in the middle of a level.

**Comment by vincetiu8** [comment]
At 1336x768 and other resolutions higher than 1280x720, there is still a black bar where the menu isn't drawn in the bottom and right of the screen.

**Comment by Graphcalibur** [comment]
Should be fixed now, and LGTM!

**Pull request merged**
