### PR TITLE
Renamed img files with extension .PNG to .png

### PR DESCRIPTION
**Pull request by Graphcalibur**

### CODE REVIEW

**Review by vincetiu8 — CHANGES_REQUESTED** [review]
Doesn't fix the errors for me, the only solution is still using #21. Maybe edit that branch to modify the bat file to run on linux?

**Comment by Graphcalibur** [comment]
The change was only made to fix FileNotFound errors as a result of img files having .PNG as their extension while the code looks for files with extension .png. I think this might only be an issue on my end, though.

I'll look into fixing the libpng error messages on Linux.

**Comment by vincetiu8** [comment]
Ah ok, looks good then.

**Review by vincetiu8 — APPROVED** [review]
LGTM!

**Pull request merged**
