### PR TITLE
Add acute mouth level

### PR DESCRIPTION
**Pull request by vincetiu8**
Sorry this took a long while because of playtesting.

This PR adds the acute mouth level, the first one the player will encounter in the game.

Enemies included:
- Common Cold
- Hepatitis A
- Hepatitis B

Bugs fixed:
- #263
- #266 
- #267 

Other changes:
- Added some changes to the game which allow for easier playtesting (to be removed later). These include:
    - An option at the start of game.py to skip to a certain level (and obtain all the protein from enemies in all the previous levels)
    - The game doesn't end if the player runs out of lives
    - Force enemies that reach the goal to drop protein anyways
- Right-click upgrades a tower
- Scroll-wheel-click sells a tower

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Received this error when trying to play the Mild Mouth level:

Traceback (most recent call last):
  File "data/game.py", line 267, in prepare_next_wave
    for i in self.level_data["waves"][self.difficulty][self.wave]:
IndexError: list index out of range

**Comment by vincetiu8** [comment]
Oops yeah, that's due to me setting the dev option in the game.py to 35 for playtesting.

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Found another issue: the timer before the next wave starts no longer does anything, so the player has infinite time to do whatever they want in between waves.

Also, I'm pretty curious what the optimal strat for the level is. I can't seem to get past Wave 11 haha

**Comment by vincetiu8** [comment]
That timer change was intentional. I'll add a comment to it.

**Comment by Graphcalibur** [comment]
LGTM then!

**Pull request merged**
