### PR TITLE
Added mitochondria and monocyte towers

### PR DESCRIPTION
**Pull request by Graphcalibur**
These two towers buff the damage and range of nearby towers, respectively. Also added support for adding AOE buff towers.

### CODE REVIEW

**Review by vincetiu8 — CHANGES_REQUESTED** [review]
Game crashes when I try to remove the aoe buff effect in the tower edit menu with the error:
```
File "D:\Vince\Documents\BSMPyGame\data\towers.py", line 214, in load_tower_data
    self.sound = data["shoot_sound"]
KeyError: 'shoot_sound'
```

**Comment by Graphcalibur** [comment]
I think that's part of a general issue with the TowerEdit menu where we deleted the unnecessary files and attributes of certain towers. For instance, since Neutrophil is an AOE attack tower, it doesn't have any gun/bullet images or the rotating/tracking attributes. So if you try to uncheck its AOE status, the game will crash. I don't want to add unnecessary files so this issue will probably stay that way.

Also, the "fixed crash error" commit doesn't fix this issue, that was for something unrelated.

**Comment by vincetiu8** [comment]
Ok, I'll just fix this in another PR.

**Review by vincetiu8 — APPROVED** [review]
LGTM!

**Pull request merged**
