### PR TITLE
Arteries and veins

### PR DESCRIPTION
**Pull request by vincetiu8**
This adds arteries and veins into the game, increasing the potential complexity of levels.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
There seems to be an issue with the yellow path not being redrawn if it changes after removing a tower. This doesn't affect the enemies (they will revert to the previous path as expected), just the drawing of the path.

Aside from this, though, it LGTM

**Comment by Graphcalibur** [comment]
Also, what's the difference between arteries and veins gameplay-wise?

**Comment by vincetiu8** [comment]
The only difference is arteries connect to arteries and vice versa. So if there is a junction between 3 arteries, the enemies can go through either one. I just thought it would be cool to have two different colors of tunnel as well so we could make more complicated intersections.

**Comment by vincetiu8** [comment]
fixed now, pls check.

**Pull request merged**
