### PR TITLE
Fix level edit

### LINKED ISSUE #166: Can't edit levels anymore
Title. Level Edit doesn't allow editing anymore.

### PR DESCRIPTION
**Pull request by vincetiu8**
Fixes #166.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
The save settings button doesn't appear.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
It still doesn't appear.

**Comment by vincetiu8** [comment]
I... didn't push the branch 🤦. Should be fixed now @Graphcalibur.

**Review by Graphcalibur — APPROVED** [review]
LGTM!

**Pull request merged**
