### PR TITLE
Level editor

### LINKED ISSUE #84: Make a level creator
Similar to #82 and #83, we should have a GUI so people can create waves and assign enemies to them.

### PR DESCRIPTION
**Pull request by vincetiu8**
This adds a level editor into the game and fixes many bugs in the existing editors.

### CODE REVIEW

**Comment by Graphcalibur** [comment]
Adding levels works as intended, but there's an issue with how the level is previewed. To create a map for my new test level, I copied map2.tmx and renamed the copy map3.tmx. When I went into the level preview, I made a new level (with number 3) and started editing the first wave. However, no matter what I did, the level preview kept playing the first wave of level 2.

Here's a demonstration of it: https://youtu.be/h8IAvr1ikbU

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
EDIT: ignore this comment, read the one above

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
The above issue seems to be fixed now. However, another one popped up while I was editing a new level. I was working on wave 0, sub-wave 1. When I tried to switch to wave 1, I got this error:

Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "data/main.py", line 49, in run
    self.events()
  File "data/main.py", line 72, in events
    result = self.current_display.event(event)
  File "data/dev_tools.py", line 489, in event
    self.reload_attrs()
  File data/dev_tools.py", line 469, in reload_attrs
    self.load_ui()
  File "data/dev_tools.py", line 392, in load_ui
    temp_val = LEVEL_DATA[self.level]["waves"][self.wave][self.sub_wave][attr]
IndexError: list index out of range

@Invincibot

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
LGTM!

**Pull request merged**
