### PR TITLE
Ties levels to the different body parts

### LINKED ISSUE #193: Tie levels to the different body parts
Instead of having big level buttons with numbers on them, it would be better if we put markers on the relevant body parts as the "level" buttons.

By the way, I was wondering if the levels should start from the mouth and go inwards into the body, or the other way around. The former is more natural, but I feel like the latter makes more sense since the body is pushing the invasion back starting from the inside.

### PR DESCRIPTION
**Pull request by Graphcalibur**
Fixes #193. I don't think the old body image worked very well for showing organs so I decided to use a different one. The level buttons also got changed to glowing red spots (like sore spots on a scientific diagram). Furthermore, maps are now tied to the body parts rather than to the levels, so if you want to change the map of a level, you have to change the body part in dev_tools.

Unrelated change, but the level editor now supports maps where viruses must traverse through arteries or veins to reach the goal.

Lastly, you might notice that changing the body part attribute in the level editor doesn't do anything until you go out of the editor than go back in again. This is intentional since there's a lot of crashes that can happen when switching through maps (since the start data might not be compatible with the map), so it just helps to reduce crashes if the map only changes when you exit the editor and go back in.

### CODE REVIEW

**Review by vincetiu8 — COMMENTED** [review]
I feel like the blurry new level buttons don't fit with the 8-bit style too well. Perhaps we could change them to smaller versions of the old level button, like points? What do you think?

**Comment by Graphcalibur** [comment]
I prefer the glowing spots since it fits more with the theme of a body with the infected spots being pointed out. Also, I tried scaling down the old level buttons but it was still pretty out of place with the 8-bit body image. I can try pixelating the glowing spots to make it fit the 8-bit aesthetic a bit more.

**Comment by Graphcalibur** [comment]
See if this is any better @Invincibot

**Review by vincetiu8 — APPROVED** [review]
Looks better now!

**Pull request merged**
