### PR TITLE
Add the Neutrophil

### PR DESCRIPTION
**Pull request by vincetiu8**
This adds a new tower, the 'neutrophil' to the game, which uses an area-of-effect radius to damage enemies.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
No bugs as far as I can tell, however I'd recommend fixing the drawing of the green square around the neutrophil so that they don't get more opaque if they overlap/

Also this can be changed some other time, but this tower is pretty broken and lets you streamroll over the Extreme level haha.

**Comment by vincetiu8** [comment]
Yeah to be fair its quite unbalanced. I'll lower the green square drawing and add an attribute that allows you to change the color.

**Comment by vincetiu8** [comment]
@Graphcalibur should be fixed now.

**Comment by Graphcalibur** [comment]
There seems to be another issue now with the non-neutrophil towers. They repeatedly play the bullet firing sound even when no bullets are being fire. Also, in a level, non-neutrophil towers will eventually stop firing bullets after a while (although the bullet firing sound still plays).

**Comment by vincetiu8** [comment]
Is this an issue unique to this pull request or an issue in general?

**Comment by Graphcalibur** [comment]
It's unique to this pull request

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
The issue with towers stopping their firing after a while still persists.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur

**Comment by Graphcalibur** [comment]
LGTM

**Pull request merged**
