### PR TITLE
More enemies 4

### PR DESCRIPTION
**Pull request by vincetiu8**
Adds more enemies. The full list can be found in the sheet.

Also massively buffs COVID, (I want to reserve it for some later levels). Its stats are transferred to the Rubella virus, and I've replaced all instances of COVID with it in the earlier levels.

### CODE REVIEW

**Comment by dyhuan** [comment]
A lot of the new enemies have a attribute error (no attribute to 'current _value').

**Comment by vincetiu8** [comment]
How are you getting the errors? I'm not getting them on mine.

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Sorry for the late review. I'm getting the same error as @Dyhuan when trying to view the Chickenpox or Shingles in the enemy preview:

  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "data/main.py", line 79, in run
    self.events()
  File "data/main.py", line 141, in events
    temp_result = self.current_display.event(event)
  File "data/dev_tools.py", line 522, in event
    self.reload_attrs()
  File "data/dev_tools.py", line 504, in reload_attrs
    self.load_ui() # has to be called so UI reloads when changing tower_name while editing a description
  File "data/dev_tools.py", line 483, in load_ui
    self.get_attr_surf()
  File "data/dev_tools.py", line 112, in get_attr_surf
    self.attr_surf = self.ui.get_ui()
  File "data/dev_tools.py", line 910, in get_ui
    attr_surf = attr.draw()
  File "data/dev_tools.py", line 1217, in draw
    cur_val_text = font.render(str(self.current_value), 1, WHITE)
AttributeError: 'Attribute' object has no attribute 'current_value'

**Comment by vincetiu8** [comment]
@Graphcalibur @Dyhuan  Should be fixed now. Also removed the depreciated level edit menu.

**Review by Graphcalibur — COMMENTED** [review]
LGTM!

**Pull request merged**
