### PR TITLE
Cache pathfinding routes

### LINKED ISSUE #88: Game crashes when removing a tower
Missed this bug when testing the multi-start PR. Removing a tower in level 2 or 3 causes the game to crash with the following error message:

Traceback (most recent call last):
  File "main.py", line 573, in <module>
    g.run_game()
  File "main.py", line 33, in run_game
    self.events()
  File "main.py", line 88, in events
    self.game.event(event)
  File "main.py", line 552, in event
    self.path = self.pathfinder.astar(tile_map, ((tile_from_xcoords(self.starts[0].x, self.map.tilesize),
AttributeError: 'Start' object has no attribute 'x'

### PR DESCRIPTION
**Pull request by vincetiu8**
This saves the pathfinding routes after calculation for faster access. Works towards #73.

### CODE REVIEW

**Comment by Graphcalibur** [comment]
LGTM but I think you should test to make sure the pathfinding still works properly after removing a tower -- presumably after resolving issue #88

**Comment by vincetiu8** [comment]
#88 should be fixed now @Graphcalibur.

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
The tower previews aren't working properly now, and don't indicate that the player can't place a tower on a tile that completely blocks off the path.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by vincetiu8** [comment]
This fixes the last issue needed before we make a release so after this we should release a version like v0.1.

**Comment by Graphcalibur** [comment]
I somehow found another weird bug with the enemy pathfinding if you move your cursor around a lot with the tower preview active: https://www.youtube.com/watch?v=Q_l40n9Au8k

This seems to only occur for enemies at the starting tile. Enemies past that have their pathfinding work just fine no matter what I do.

**Comment by vincetiu8** [comment]
Can't replicate this on my end, could you investigate the conditions of the issue on your end?

**Comment by vincetiu8** [comment]
This may have patched it but not sure @Graphcalibur.

**Comment by Graphcalibur** [comment]
Yeah, that seemed to fix the issue. LGTM

**Pull request merged**
