### PR TITLE
New maps

### PR DESCRIPTION
**Pull request by vincetiu8**
Adds maps for every body part except for the heart.

Other bug fixes:
- Towers can no longer be placed on arteries.
- Fixed enemy pathfinding.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Some of these maps are really cool! I especially like the lung one, that one is insane.

Some issues I found:
- In Small Intestine and Liver, the pathfinding doesn't seem to register arteries/veins properly and will ignore it even if it's the optimal route. Also, towers can still be placed on arteries/veins in the Small Intestine map.
- Enemy targeting AI gets kind of strange when arteries are taken into play. This is most notable in the Large Intestine map where if towers are placed near the artery opening in the leftmost section, they will eventually stop shooting at the enemies. This can be addressed in a future PR though.

**Comment by vincetiu8** [comment]
> In Small Intestine and Liver, the pathfinding doesn't seem to register arteries/veins properly and will ignore it even if it's the optimal route.  

This is a pre-existing issue, and i will address it in a different PR.

> Enemy targeting AI gets kind of strange when arteries are taken into play. This is most notable in the Large Intestine map where if towers are placed near the artery opening in the leftmost section, they will eventually stop shooting at the enemies. This can be addressed in a future PR though.  

Same.

**Comment by vincetiu8** [comment]
I can't replicate placing towers on arteries or veins on the small-intestine map or the liver map. Are you sure you have the latest branch?

**Comment by Graphcalibur** [comment]
Yeah it's up to date. In the Small Intestines map, I first placed a tower on the tile above the topmost vein entrance. After that, the game lets you place towers on the artery/vein entrances in that map/

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
Found another issue. This error shows up if you try going to the Tower/Enemy/Level previews and editors:

```AttributeError: 'TowerEditMenu' object has no attribute 'map_objects'```

**Comment by vincetiu8** [comment]
Oops, should be fixed now.

Note: that error results from me dropping support for map objects since now enemies shrink fast enough that we don't need the artery and vein overlays, saving time when making levels.

**Comment by Graphcalibur** [comment]
LGTM!

**Pull request merged**
