### PR TITLE
Added enemy waves

### PR DESCRIPTION
**Pull request by Graphcalibur**
Addresses issue #29. The wave data of each level is now stored using JSON files, with each file corresponding to a level. The attributes of the wave consist of the enemy type, the enemy count, the delay before the enemies start spawning, and the spawn rate. A wave can have multiple enemy types, and each enemy type can have different attributes from other enemy types in the same wave.

Not all functionality of enemy waves have been added yet, as addressed in my comment in issue #29.

### CODE REVIEW

**Comment by vincetiu8** [comment]
This errors out if we win the game. Let's just add a simple 'you won' instead of the gameover text and then pull the branch after.

**Review by vincetiu8 — CHANGES_REQUESTED** [review]
JSON looks good but let's add a commit so the game doesn't error out if we win first. Just reuse the game over text for now. Perhaps after they win the user can press a key so they return to the levels menu.

**Comment by Graphcalibur** [comment]
There should be a "win" state now. I just reused the game over code but with different text, though.

**Comment by vincetiu8** [comment]
Uh it doesn't want to launch now. This may be due to my tinkering with the main.py to get the game to launch. Pls check @Graphcalibur.

**Comment by Graphcalibur** [comment]
Launches fine for me.

**Comment by vincetiu8** [comment]
LGTM!

**Review by vincetiu8 — APPROVED** [review]
LGTM!

**Pull request merged**
