### PR TITLE
Mapping

### PR DESCRIPTION
**Pull request by vincetiu8**
This changes and will probably break a lot of stuff, so I would suggest reviewing this heavily. 

Added features:
- A Tiled test map using actual tiles to simulate a real level.
- Imports tilesize, width and height from the Tiled map
- Imports background and walls (obstacles) from the Tiled map
- Enables the player to zoom in and out of the screen
- Adds a basic tower
- Enables towers to be removed using right-click
- Fixes pathfinding of enemies

### CODE REVIEW

**Comment by Graphcalibur** [comment]
Tried deleting a tower and I got this error:

Traceback (most recent call last):
  File "main.py", line 195, in <module>
    g.run()
  File "main.py", line 45, in run
    self.events()
  File "main.py", line 171, in events
    self.path = astar(tile_map, (tile_from_xcoords(self.start.x, self.map.tilesize),
UnboundLocalError: local variable 'tile_map' referenced before assignment

**Comment by vincetiu8** [comment]
Ah let me look at this.

**Comment by vincetiu8** [comment]
I fixed the error, please check on ur machine now. @Graphcalibur

**Review by dyhuan — APPROVED** [review]
LGTM

**Pull request merged**
