### PR TITLE
Libpng error

### PR DESCRIPTION
**Pull request by vincetiu8**
This includes a bat file and instructions on how to remove the libpng error, resolving #20.

### CODE REVIEW

**Comment by Graphcalibur** [comment]
Can't test this since I'm running my code in Linux. Someone else has to test and merge this.

**Comment by Graphcalibur** [comment]
Added linux version.

Also, I'll test this on a windows computer later today.

**Comment by vincetiu8** [comment]
I'll check the linux.

**Comment by Graphcalibur** [comment]
I downloaded the "ImageMagick-7.0.10-1-Q16-x64-dll.exe" file on windows and installed it. I tried an imagemagick option out in the command line and it seems to work properly. When I run the bat file, however, it gives the following errors multiple times:

'identify' is not recognized as an internal or external command,
operable program or batch file.
Invalid Parameter - -strip

The program also still outputs the libpng error messages.

**Comment by vincetiu8** [comment]
You need to install the legacy version?

**Comment by Graphcalibur** [comment]
I got it to work after downloading the legacy version. I'll edit the Readme to make that clearer. Is the Linux script working fine?

**Comment by vincetiu8** [comment]
I'm getting
`./img_fixer.sh: line 7: convert: command not found`
on linux when executing the script. Any ideas why?

**Comment by Graphcalibur** [comment]
Do you have ImageMagick installed and did you follow the download instructions on the website? It's a bit complicated unless you use a package manager.

**Comment by vincetiu8** [comment]
I was using apt-get to do it, do I need to use RPM?

**Comment by Graphcalibur** [comment]
Hm it should work if you installed it using apt-get. I guess we can just push the updated images to the repository so it's not a big deal though.

**Comment by vincetiu8** [comment]
Rip just remove Mr. Denton's image before we pull this then.

**Pull request merged**
