### PR TITLE
More levels

### PR DESCRIPTION
**Pull request by vincetiu8**
Things added:
- More levels
- Ability to have more than 1 goal
- Ability to have a start larger than 1 tilesize (randomly spawns enemies in it)

Things fixed:
- Enemy pathfinding with more than 1 goal
- The tilesets
- The start menu

For some reason sometimes enemies fail to find a path randomly. Currently, I've said to just kill them if they can't find a path but we may need to look into this later.

### CODE REVIEW

**Comment by Graphcalibur** [comment]
map1.tmx seems to be missing from the commit, which causes the game to crash.

I also feel like having multiple enemy paths (due to multiple goals and starts) in conjunction with the embellished enemy movement makes things too confusing. Keeping only one or the other would be better.

**Comment by vincetiu8** [comment]
Added the missing map. That is true though, but it would be cool to have multiple starts or multiple goals. Perhaps we can add a feature that causes an error if there are multiples of both?

**Comment by Graphcalibur** [comment]
I got another error when starting Level 2:

Traceback (most recent call last):
  File "main.py", line 538, in <module>
    g.run_game()
  File "main.py", line 34, in run_game
    self.update()
  File "main.py", line 45, in update
    elif self.game.update() == False:
  File "main.py", line 310, in update
    self.enemies.update()
  File "/usr/lib/python3.8/site-packages/pygame/sprite.py", line 463, in update
    s.update(*args)
  File "enemies.py", line 53, in update
    if (self.rect.left <= self.new_node_rect.left):
AttributeError: 'Enemy' object has no attribute 'new_node_rect'

**Comment by vincetiu8** [comment]
Should be good now @Graphcalibur.

**Comment by Graphcalibur** [comment]
LGTM but I've gotten some "PATHFINDING ERROR"s printed out in the 2nd level when I place a tower and cause the path to be recalculated. Will this cause any problems?

**Comment by vincetiu8** [comment]
This should be good now @Graphcalibur.

**Pull request merged**
