### PR TITLE
Add UI to game

### PR DESCRIPTION
**Pull request by dyhuan**
Added protein and lives to top left corner. It changes every time an enemy gets past or or an enemy gets killed, respectively.

### CODE REVIEW

**Comment by vincetiu8** [comment]
I think the UI needs a rectangle in the background first before it is added...

**Comment by Graphcalibur** [comment]
I think the "Lives" and "Protein" should be represented using symbols instead of words so it can be easily fit into the top portion of the game screen.

**Comment by vincetiu8** [comment]
@Graphcalibur I cleaned this up, please check again. Expect a few errors after merging though since this branch was started so long ago.

**Comment by Graphcalibur** [comment]
This is starting to get messy as a lot of the code in this branch is old and unused. I'll see if I can clean up the unnecessary bits.

**Comment by vincetiu8** [comment]
No need I'll just redo it on master.

**Comment by vincetiu8** [comment]
Branch too old, moved to #44

**Pull request closed without merging**
