### PR TITLE
Dev cleanup

### LINKED ISSUE #107: Clean up dev_tools code
Right now it's really messy and there's a lot of copy-pasted code between EnemyPreview and TowerPreview. It would be a lot cleaner if we can have a parent Preview class that TowerPreview and EnemyPreview inherit from so it'd be a lot easier to make any changes to them.

### PR DESCRIPTION
**Pull request by vincetiu8**
Fixes #107 and adds a solid base for #84.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
The attributes no longer update when changing the tower/enemy type. Also, the collision detection for the buttons is a bit strange. It seems like you have to click on the text itself; clicking on the area in the button but without any text does nothing.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
The attribute issue is gone now though I got this error when clicking "Done" in the tower preview menu:

Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "/data/main.py", line 50, in run
    self.events()
  File "/data/main.py", line 76, in events
    result = self.current_display.event(event)
  File "/data/dev_tools.py", line 239, in event
    result = super().event(event)
  File "/data/dev_tools.py", line 146, in event
    name = result.name
AttributeError: 'str' object has no attribute 'name'

The buttons are also still a bit iffy and only work if you click on the text.

**Comment by vincetiu8** [comment]
should be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
There are some merge conflicts. Also I'm getting this really weird bug: sometimes, when I click the +/- buttons in the Enemy Preview to change the enemy attributes, the game crashes with this error:

Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "/data/main.py", line 50, in run
    self.events()
  File "/data/main.py", line 87, in events
    self.set_display(self.display_keys[result], args)
KeyError: <data.dev_tools.Attribute object at 0x7f9784753a00>

**Comment by vincetiu8** [comment]
I'm having trouble replicating the bug on my end. Have you pulled the latest branch?

**Comment by Graphcalibur** [comment]
I've pulled the latest commits from this branch. Best way I found to get this bug to occur is to spam click the various +/- buttons for HP, Speed, and Protein in the Enemy Preview window. It should occur eventually.

**Comment by vincetiu8** [comment]
The bugfix should have fixed issues that arise from that, and I also can't replicate it by spamming buttons on mine. Could you look into it from your end?

**Comment by vincetiu8** [comment]
Hmm that's weird. I've never experienced that...

**Comment by Graphcalibur** [comment]
OK I think I've managed to fix it now. Turns out the bug occurred when you clicked slightly underneath one of the buttons. LGTM

**Pull request merged**
