### PR TITLE
Updates master to create a new stable release version

### PR DESCRIPTION
**Pull request by Graphcalibur**
The edit menus have all been removed from access, and the save file has been reverted to the starting save data.

Let me know if there's anything that needs changing or if there are still issues that need to be addressed before making a new stable release.

### CODE REVIEW

**Comment by vincetiu8** [comment]
Hol up, just one last thing I'd like to add before we merge. Imma make a PR on it today.

**Comment by vincetiu8** [comment]
Sorry it took longer than expected, but please review #260.

**Comment by Graphcalibur** [comment]
See if there are any issues left @Invincibot

**Comment by vincetiu8** [comment]
I don't see any, LGTM! Let's merge!

**Pull request merged**
