### PR TITLE
Enemy and Spawn timers now pause when dragging window

### LINKED ISSUE #93: Enemies lag when screen is moved around
Can we make it so the game auto pauses when the screen is moved?

### PR DESCRIPTION
**Pull request by Graphcalibur**
"Fixes" #93. Trying to figure out how to get the enemy timer to pause when dragging the window is a lot trickier than I expected. I ended up just making the game fullscreen since it was a lot easier.
EDIT: See newest post.

Also, the lives counter will now never go below 0

### CODE REVIEW

**Review by vincetiu8 — CHANGES_REQUESTED** [review]
2 Things:
- I think fullscreen is a bit drastic of a change. I like it but we should in the future have the option to swap back to windowed (especially for testing) If we are going to default to fullscreen, we should have a button in the menu to exit the game as users can't simply 'exit' the game anymore.
- I think the best solution to stopping the game when being dragged is simply to pause the game if the FPS drops too low, perhaps below 20 FPS or greater than 0.05 delta time per frame.

**Comment by Graphcalibur** [comment]
I tried solution #2 but the enemies still move away from their position before the game can switch to the pause screen. I'll try having all the enemies and the spawn timers pause their timers when they detect the FPS drop.

**Comment by Graphcalibur** [comment]
OK this is really annoying...no matter where I put self.clock.tick() in the code, there seems to be a few ticks between when the game detects that the FPS has dropped and when the player stops dragging the window, which is enough delay for the enemies to move out of position before I can switch to the pause menu. There doesn't seem to be any way to let the game detect when the player starts dragging the window, either.

**Comment by Graphcalibur** [comment]
Nevermind, I managed to get the enemy and spawn timers to pause properly when dragging the window by having them count time using Main's self.clock object instead of pg.time. Also has the convenience of automatically pausing the timers when switching to the Pause menu. Hopefully this fixes things @Invincibot 

Let me know if there are any other objects in the game that use pg.time() to check time instead of the clock

**Comment by vincetiu8** [comment]
LGTM!

**Pull request merged**
