### PR TITLE
Added a new Game Over screen

### PR DESCRIPTION
**Pull request by Graphcalibur**
This partially addresses #57. "Restart" and "Back to Level Select" are now changed to buttons instead of keys. Might still add more to the screen in the future. 

Win screen to be added soon...

### CODE REVIEW

**Review by vincetiu8 — COMMENTED** [review]
Looks good, but the game over screen is still displayed when we win the game, with the cause of death 'Ib'. Any reason why this would be?

**Comment by Graphcalibur** [comment]
I haven't made the win screen yet, so that's just a placeholder for now.

**Comment by Graphcalibur** [comment]
Win screen should look different now with white text instead of red. Can't think of a better idea for it atm.

**Review by vincetiu8 — APPROVED** [review]
LGTM!

**Pull request merged**
