### PR TITLE
Level update

### PR DESCRIPTION
**Pull request by vincetiu8**
This adds a bunch to level functionality:
- Levels now inherit their 'title' from the name of the body part they are located in.
- Levels now have multiple difficulty settings:
    - 'Mild'
    - 'Acute'
    - 'Severe'
- Players need to complete previous difficulties to unlock the next ones
- Harder difficulties give more protein if completed as a bonus
- Added more locations to the body:
    - Stomach
    - Pancreas
    - Gall Bladder
    - Liver

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Got this error after beating Mouth Acute and then trying to hover over the Mouth level button:

Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "data/main.py", line 67, in run
    self.draw()
  File "data/main.py", line 76, in draw
    surf = self.current_display.draw()
  File "data/menus.py", line 181, in draw
    self.level_infos[self.over_level] = new_level_info.draw()
  File "data/menus.py", line 606, in draw
    self.make_other_info()
  File "data/menus.py", line 657, in make_other_info
    while SAVE_DATA["levels"][self.level][max_diff]:
IndexError: list index out of range

**Comment by vincetiu8** [comment]
Should be working now @Graphcalibur.

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Got this error when trying to start Mouth on Acute difficulty:
Traceback (most recent call last):
  File "sergeant_t_cell.py", line 5, in <module>
    g.run()
  File "/data/main.py", line 64, in run
    self.events()
  File "/data/main.py", line 104, in events
    self.set_display(self.display_keys[result], args)
  File "/data/main.py", line 107, in set_display
    display.new(args)
  File "/data/game.py", line 59, in new
    self.new_game()
  File "/data/game.py", line 153, in new_game
    self.prepare_next_text()
  File "/data/game.py", line 214, in prepare_next_text
    self.textbox.finish_text()
  File "/data/game_misc.py", line 250, in finish_text
    self.draw()
  File "/data/game_misc.py", line 223, in draw
    text = textwrap.fill(self.current_text, 57)  # No idea how to really calculate this.
  File "/usr/lib/python3.8/textwrap.py", line 391, in fill
    return w.fill(text)
  File "/usr/lib/python3.8/textwrap.py", line 363, in fill
    return "\n".join(self.wrap(text))
  File "/usr/lib/python3.8/textwrap.py", line 351, in wrap
    chunks = self._split_chunks(text)
  File "/usr/lib/python3.8/textwrap.py", line 337, in _split_chunks
    text = self._munge_whitespace(text)
  File "/usr/lib/python3.8/textwrap.py", line 154, in _munge_whitespace
    text = text.expandtabs(self.tabsize)
AttributeError: 'list' object has no attribute 'expandtabs'

**Comment by vincetiu8** [comment]
Can't replicate on my end. Are you sure you haven't changed the level0.json and have used the one in this branch?

**Comment by Graphcalibur** [comment]
Yeah, this is what's in my levels0.json file:

[deleted to save space]

**Comment by vincetiu8** [comment]
Could you try deleting the local branch and pulling this one?

**Comment by Graphcalibur** [comment]
Tried it, still no change

**Comment by vincetiu8** [comment]
Could you try and fix this on your end? I can't replicate and deleted and re-pulled the branch as well.

**Comment by Graphcalibur** [comment]
Made a commit to fix it. Found another issue, though. The game crashes when clicking the "<" button for the waves on the tower select menu with this error: https://i.imgur.com/zF4S8Fj.png

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Review by Graphcalibur — APPROVED** [review]
LGTM!

**Pull request merged**
