### PR TITLE
Improved UI

### LINKED ISSUE #28: Add a UI to the game
It would be nice if players could look somewhere on the screen (top right?) that has all the information such as:
- Lives
- Protein

### PR DESCRIPTION
**Pull request by vincetiu8**
Improves the UI to add towers and adds the B Cell tower into the game. It fires antibodies in multiple directions but doesn't track enemies. Level is now unbalanced.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
I'm getting this crash error whenever I try to place down a tower without first selecting one.

Traceback (most recent call last):
  File "main.py", line 455, in <module>
    g.run_game()
  File "main.py", line 29, in run_game
    self.events()
  File "main.py", line 74, in events
    self.game.event(event)
  File "main.py", line 402, in event
    if self.protein < TOWER_DATA[self.current_tower][0]["upgrade_cost"]:
KeyError: None

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur, please check again.

**Comment by Graphcalibur** [comment]
That crash error got fixed but now I can't seem to upgrade the towers anymore.

**Comment by vincetiu8** [comment]
Ok fixed the new crash err now. Pls check @Graphcalibur.

**Comment by Graphcalibur** [comment]
LGTM

**Pull request merged**
