### PR TITLE
Enemy editor

### LINKED ISSUE #83: Make an enemy preview menu
Similar to #82, we should have a GUI so non-coders can create enemies, assign attributes to them and test them in levels.

### PR DESCRIPTION
**Pull request by vincetiu8**
Adds an enemy preview editor so people can edit enemy data and add new enemies into the game. Note the enemy image and death sounds must be in the right folders when creating an enemy, otherwise it will error out. Fixes #83.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Couple of things:
- Enemy Preview button is cut off by the bottom of the screen and should be moved higher. Maybe the "Tower Preview" and "Enemy Editor" fonts should be smaller?
- I'm not entirely sure what the number next to the enemy is for

Since this seems to be forked off the same branch as #96 I'll defer merging until the issues to that have been fixed as well.

**Comment by vincetiu8** [comment]
The number next to the enemy is for the level of the towers: Some enemies may be so powerful level 1 towers can't kill them and it would be nice to check other towers (maybe) can.

Also, you can scroll around the menu screen. I'll fix this so we can do it with arrow keys, but its possible by zooming into and out of the screen.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Comment by vincetiu8** [comment]
LGTM!

**Comment by vincetiu8** [comment]
Oops wrong PR.

**Pull request merged**
