### PR TITLE
Add a acute mouth level

### PR DESCRIPTION
**Pull request by vincetiu8**
This also adds several other changes:
- Fixes issue with UI when there are more than 9 waves
- Buffs enemy hp as a level progresses
- Buffs enemy hp based on difficulty
- Increments tower cost based on difficulty
- Fixes wave number issues
- Changes health bar to a logarithmic scale

Note: the level isn't done yet, but I want to integrate the rest of these changes already.

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Got this error when playing through wave 4 of the Acute Mouth level:

File "data/game.py", line 238, in prepare_next_text
    if not SAVE_DATA["skip_text"] and len(self.level_data["texts"][self.difficulty][self.wave + 1]) > 0:  
IndexError: list index out of range

Also, the wave counter still goes above the max wave at the end of the level.

**Comment by vincetiu8** [comment]
I can't replicate the error, but the wave counter surpassing the max has been fixed. Are you sure the level00.json hasn't been changed?

**Comment by Graphcalibur** [comment]
Yeah the level00.json in my local branch is the same as the one in this. I think I've figured out the error, though, so I'll just fix it on my end then push the changes.

**Review by Graphcalibur — APPROVED** [review]
LGTM!

**Pull request merged**
