### PR TITLE
Tower overlay

### PR DESCRIPTION
**Pull request by vincetiu8**
This adds a tower overlay/ui to the game. Changes made:
- When players click on a tower the ui changes to display the tower
    - The ui displays the damage and speed of the tower
    - The ui displays the number of enemies hit and killed by the tower
    - The ui displays options to sell or upgrade the tower 
- When players have selected a tower its range is shown
- When players are placing a tower its range is shown
- In all previews the tower's ranges are shown
- Tower range check changed from diamond to a circle (note: new 'manhattan' method added to the pathfinding for this)

### CODE REVIEW

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
The monocyte (range-boosting) cell seems to be broken now and doesn't increase the range properly. This is most easily seen by placing a t-cell and then placing a monocyte next to it--the range of the t-cell actually gets smaller afterwards.

**Comment by vincetiu8** [comment]
Should be fixed now @Graphcalibur.

**Review by Graphcalibur — CHANGES_REQUESTED** [review]
Still some issues with the monocyte tower:
- Tower range isn't increased if the tower is placed after the monocyte
- If a tower has its range increased from a monocyte tower, it will lose the range boost once it's upgraded

I also got this error in the Tower Preview Menu: https://i.imgur.com/kVo3NMW.png

**Comment by vincetiu8** [comment]
Should all be fixed now @Graphcalibur.

**Comment by Graphcalibur** [comment]
Mostly looks good now, only issue is that upgrading monocyte to stage 2 doesn't further increase the range of all the towers already in its range.

**Comment by vincetiu8** [comment]
Should be good now @Graphcalibur.

**Comment by Graphcalibur** [comment]
There doesn't seem to be any new changes.

**Comment by vincetiu8** [comment]
Sorry, it should be pushed now.

**Comment by Graphcalibur** [comment]
No more problems with the monocyte now. However, I just found out one last issue - you can no longer "return" selected towers by clicking their icon in the UI. If you select a tower, you're stuck with it until you place it down.

**Comment by vincetiu8** [comment]
Fixed now.

**Comment by Graphcalibur** [comment]
The issue still seems to be there. I'm referring to how, when you select a tower from the UI to place it down, you can no longer "return" it by clicking on the tower image in the UI again and go back to not trying to place any tower down.

**Comment by vincetiu8** [comment]
Oh, I made it so you deselect a tower by putting it on an invalid tower tile or out of bounds.

**Review by Graphcalibur — APPROVED** [review]
Ah, I see. LGTM then!

**Pull request merged**
