### PR TITLE
Towers now change sprites when upgrading

### PR DESCRIPTION
**Pull request by Graphcalibur**
Also added the naive T-cell, effector T-cell, and Eosinophil/Acidophil sprites (the latter two are upgrades of naive T-cell). Lastly, this commit fixes a small bug where towers couldn't be upgraded if the current protein was less than the buy cost.

### CODE REVIEW

**Review by vincetiu8 — CHANGES_REQUESTED** [review]
This all looks good, but the game crashes if we try to upgrade a tower past its max level.

**Comment by Graphcalibur** [comment]
Should be fixed now, can you try it again @Invincibot

**Comment by vincetiu8** [comment]
This doesn't have seemed to fix this. I'm getting the error:
`base_image = tower.base_images[tower.stage]
IndexError: list index out of range`
Could you check this on your side?

**Comment by Graphcalibur** [comment]
No issues of that sort on my end

**Review by vincetiu8 — APPROVED** [review]
Issue cleared up on my end, LGTM!

**Pull request merged**
